/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CreatePokemonForm: typeof import('./src/components/CreatePokemonForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    PokemonList: typeof import('./src/components/PokemonList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
