kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000
        hostPort: 3000
        protocol: TCP
      - containerPort: 3001
        hostPort: 3001
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
