apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fantasy-pokedex.fullname" . }}
  labels:
    app: {{ include "fantasy-pokedex.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fantasy-pokedex.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fantasy-pokedex.name" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
            - containerPort: 3001 # healthz server
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          # probes removed
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            {{- range $key, $value := .Values.backend.env }}
            {{- if and (eq $key "DB_PASS") (ne $.Values.backend.secret.dbPassSecret "") }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.backend.secret.dbPassSecret }}
                  key: DB_PASS
            {{- else if and (eq $key "ADMIN_PASSWORD") (ne $.Values.backend.secret.adminPasswordSecret "") }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.backend.secret.adminPasswordSecret }}
                  key: ADMIN_PASSWORD
            {{- else }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
          # probes removed
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
