apiVersion: v1
kind: Service
metadata:
  name: {{ include "fantasy-pokedex.fullname" . }}-frontend
  labels:
    app: {{ include "fantasy-pokedex.name" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
  selector:
    app: {{ include "fantasy-pokedex.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fantasy-pokedex.fullname" . }}-backend
  labels:
    app: {{ include "fantasy-pokedex.name" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      name: http
  selector:
    app: {{ include "fantasy-pokedex.name" . }}
